### ISSUE TITLE
Открытие вкладки

### ISSUE THREAD

**Issue by oreshkin-ay** [yndx-shri-reviewer/shri-2020-task-3#2]
"Если превью уже открыто, то должна открываться уже открытая вкладка, новая открываться не должна."
![image](https://user-images.githubusercontent.com/17002069/69967883-56f61900-152a-11ea-8a89-06d8f324bbce.png)
Сейчас открыто превью для index.json. Правильно ли я понял, что при открытии product.json, она должна открываться на месте index. Или это уже другой документ-другая панель?

**Comment by dima117** [comment]
Превью для каждого документа нужно открывать отдельно.
