### ISSUE TITLE
Подключение линтера

### ISSUE THREAD

**Issue by RuslanGerasimov** [yndx-shri-reviewer/shri-2020-task-3#3]
> Подключите в проект линтер из второго задания.

Линтер из второго задания должен заменить линтер-заглушку или дополнить? Нужно ли предусмотреть настройку типа ошибок (Error, Warning, ...) для правил линтера из второго задания?

**Comment by dima117** [comment]
Если вы просто замените линтер, то мы не сможем понять, исправили ли вы ошибки в его работе. В идеале, нужно исправить все ошибки, потом создать ветку из этого состояния и подключить туда линтер из второго задания.

> Нужно ли предусмотреть настройку типа ошибок (Error, Warning, ...) для правил линтера из второго задания?

Если сделаете, это будет плюсом к вашей работе.
