### ISSUE TITLE
Очистка окна с ошибками после закрытия файла json

### ISSUE THREAD

**Issue by bemdev** [yndx-shri-reviewer/shri-2020-task-3#6]
Нормально или нет, если после закрытия json файла но не редактора в логе ошибок показываются ошибки открытых ранее файлов?

или надо дополнительно удалить?

**Comment by dima117** [comment]
должно быть стандартное поведение, как у остальных линтеров

**Comment by rakov-di** [comment]
@dima117 хм... явный ответ на этот вопрос тоже считается подсказкой? 
А на этот: можно ли считать "стандартным" поведение расширения для vscode TSLint?

**Comment by dima117** [comment]
да
